export default {
	port: '',
	dbUrl: '',
	accessTokenSecret: 'daDSBSJDBJSBD324542NKDNKSNDKND',
	accessTokenExpiry: '1h',
	refreshTokenSecret: 'daDSBSJDBJSBD324542NKDNKSNDKNDdsdsdsdsd#dsdsdsd',
	refreshTokenExpiry: '7d',
	// origin: 'https://hmx-subhambharadwaz.vercel.app',
	origin: 'http://localhost:3000',
	redisUrl: 'redis://localhost:6379',
	cloudinaryName: '',
	cloudinaryApiKey: '',
	cloudinaryApiSecret: '',
	smtpHost: '',
	smtpPort: '',
	smtpUser: '',
	smtpPass: '',
	stripeApiKey: '',
	stripeApiSecret: '',
	razorpayApiKey: '',
	razorpayApiSecret: '',
	userImageDir: 'users',
	productImageDir: 'products'
};
