export default {
	port: 4000,
	dbUrl: '',
	jwtSecret: 'daDSBSJDBJSBD324542NKDNKSNDKND',
	jwtExpiry: '3d',
	origin: 'http://localhost:3000',
	cloudinaryName: '',
	cloudinaryApiKey: '',
	cloudinaryApiSecret: '',
	smtpHost: '',
	smtpPort: '',
	smtpUser: '',
	smtpPass: '',
	stripeApiKey: '',
	stripeApiSecret: '',
	razorpayApiKey: '',
	razorpayApiSecret: '',
	userImageDir: 'users',
	productImageDir: 'products'
};
