export default {
	port: '',
	dbUrl: '',
	jwtSecret: 'daDSBSJDBJSBD324542NKDNKSNDKND',
	jwtExpiry: '3d',
	origin: 'https://hmx-e6tu01j2i-subhambharadwaz.vercel.app',
	redisUrl: 'redis://localhost:6379',
	cloudinaryName: '',
	cloudinaryApiKey: '',
	cloudinaryApiSecret: '',
	smtpHost: '',
	smtpPort: '',
	smtpUser: '',
	smtpPass: '',
	stripeApiKey: '',
	stripeApiSecret: '',
	razorpayApiKey: '',
	razorpayApiSecret: '',
	userImageDir: 'users',
	productImageDir: 'products'
};
