version: '3.7'
services:
    hmx-rest-api:
        container_name: hmx-rest-api
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        build:
            context: ./
        ports:
            - 4000:4000

    # caddy:
    #     image: caddy/caddy:2.2.1-alpine
    #     container_name: caddy-service-hmx
    #     restart: unless-stopped
    #     port:
    #         - '80:80'
    #         - '443:443'
    #     volumes:
    #         - $PWD/Caddyfile:/etc/caddy/Caddyfile
    #         - $PWD/site:/srv
    #         - caddy_data:/data
    #         - caddy_config:/config

    # volumes:
    #     caddy_data:
    #     caddy_config:
