openapi: '3.0.0'
info:
    title: hmx
    description: An E-commerce API for jogger store
    version: 1.1.0
    contact:
        email: 'subhamsbharadwaz@gmail.com'
        url: 'https://www.github.com/subhamBharadwaz'

servers:
    - url: '{protocol}://{url}/api/{version}'
      description: for local host
      variables:
          version:
              enum:
                  - v1
                  - v2
              default: v1
          url:
              enum:
                  - localhost:4000
              default: localhost:4000
          protocol:
              enum:
                  - http
                  - https
              default: http

components:
    securitySchemes:
        cookieAuth:
            type: apiKey
            in: cookie
            name: token
        BearerAuth:
            type: http
            scheme: bearer

paths:
    /register:
        post:
            tags:
                - User
            summary: register a new user, required fields - firstName, lastName, email, password(must be minimum 8 characters long and contains at least 1 uppercase, 1 lowercase, 1 number and 1 symbol) and photo
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            required:
                                - firstName
                                - lastName
                                - email
                                - password
                                - photo
                            properties:
                                firstName:
                                    type: string
                                    required: true
                                lastName:
                                    type: string,
                                    required: true
                                email:
                                    type: string,
                                    required: true
                                password:
                                    type: string,
                                    required: true
                                photo:
                                    in: formData
                                    description: The uploaded file data
                                    type: file
                                    format: binary
                                    required: true
            responses:
                200:
                    description: All good success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                    token:
                                        type: string
                400:
                    description: Bad request
                500:
                    description: Internal server error

    /login:
        post:
            tags:
                - User
            summary: login user, required fields -  email, password
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - email
                                - password
                            properties:
                                email:
                                    type: string,
                                    default: 'one@gmail.com'
                                    required: true
                                password:
                                    type: string,
                                    default: 'Subham12@'
                                    required: true
            responses:
                200:
                    description: All good success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                    token:
                                        type: string
                400:
                    description: Bad request
                500:
                    description: Internal server error

    /logout:
        get:
            tags:
                - User
            summary: get request to logout the user. Also removes httpOnly cookies
            responses:
                200:
                    description: All good success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                    token:
                                        type: string
                400:
                    description: Bad request
                500:
                    description: Internal server error

    /forgotpassword:
        post:
            tags:
                - User
            summary: sends an email with link to forgot password. Contains the token for user validation. Public hosted version will not send email to your account. Use your own SMTP details to access this feature on local project
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - email
                            properties:
                                email:
                                    type: string
                                    default: 'example.com'
            responses:
                200:
                    description: All good success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                    token:
                                        type: string
                400:
                    description: Bad request
                500:
                    description: Internal server error

    /password/reset/:token:
        post:
            tags:
                - User
            summary: Allows user to reset password, validated based on token, send password and confirm password fields
            parameters:
                - name: token
                  in: path
                  required: true
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - password
                                - confirmPassword
                            properties:
                                password:
                                    type: string
                                confirmPassword:
                                    type: string

            responses:
                200:
                    description: All good success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                    token:
                                        type: string
                                    message:
                                        type: string
                400:
                    description: Bad request
                500:
                    description: Internal server error

    /userdashboard:
        get:
            tags:
                - User
            summary: Gets all details about logged in user, send token in cookies as named token or send Bearer Auth
            requestBody:
            responses:
                200:
                    description: All good success
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                    token:
                                        type: string
                                    user:
                                        type: object
                                        properties:
                                            name:
                                                type: string
                                            email:
                                                type: string
                                            role:
                                                type: string
                                            photo:
                                                type: object
                                                properties:
                                                    id:
                                                        type: string
                                                    secure_url:
                                                        type: string
                                            _id:
                                                type: string
                                            createdAt:
                                                type: string
                                            updatedAt:
                                                type: string
                400:
                    description: Bad request
                500:
                    description: Internal server error
